### ISSUE TITLE
Can't connect host docker client to VM on explicit IP

### ISSUE THREAD

**Issue by posita** [Parallels/boot2docker-vagrant-box#17]
I'm using [this `Vagrantfile`](https://github.com/posita/vagrant-b2d-nfs-test/blob/59101c7a45757025e79811c535f3450c7f7fadd8/Vagrantfile). Note (from [L20](https://github.com/posita/vagrant-b2d-nfs-test/blob/59101c7a45757025e79811c535f3450c7f7fadd8/Vagrantfile#L20); `VM_IP_ADDR` defaults to `10.1.2.3`):

```ruby
...
        vagrant_b2d_nfs_test.vm.network(:private_network, ip: VM_IP_ADDR)
...
```

When I attempt to connect to the explicit IP from the host, I'm rejected. It looks like the certificate only accommodates `localhost` and the dynamic IP set by Vagrant:

```sh
% DOCKER_HOST=tcp://10.1.2.3:2376 DOCKER_TLS_VERIFY=0 DOCKER_CERT_PATH="${PWD}/certs" docker images
FATA[0000] An error occurred trying to connect: Get https://10.1.2.3:2376/v1.18/images/json: x509: certificate is valid for 127.0.0.1, 10.211.55.239, not 10.1.2.3
```

See also dduportal/boot2docker-vagrant-box#30.

**Comment by legal90** [comment]
I couldn't reproduce an issue from the scratch on the box v1.7.1, e.q. there is no such error message. But even so, it is not related to the box itself.
It is caused by the fact that Docker generates certificates _before_ then the Vagrant configures private network interface. I suppose, it should help:
```
vagrant_b2d_nfs_test.vm.provision :shell, inline: "sudo /etc/init.d/docker restart"
```
https://github.com/boot2docker/boot2docker/blob/63fc76258902d563ba80a2ebd75d5318bbc5fb20/doc/WORKAROUNDS.md#connection-issues

**Comment by dduportal** [comment]
Hello, just to let you know that I encountered race conditions when tuning the Docker Daemon (especially when running some containers that take time to propagate signals) by adding  provisioning phase with the restart. Hope it'll helps :)
